### ISSUE TITLE
Create Timestamp

### ISSUE THREAD

**Issue by AnasShafqat** [DEXDEVS/School-App#4]
### _**Timestamp is required for the following fileds**_

1. **created_at**
2. **updated_at**
3. **created_by**
4. **updated_by**

**Comment by Kinza59** [comment]
**Timestamp fields are populating automatically:**

in controller:

actionCreate() {
$model->created_by = Yii::$app->user->identity->id; 
                $model->created_at = new \yii\db\Expression('NOW()');
                $model->updated_by = '0';
                $model->updated_at = '0'; 
                $model->save();
}


actionUpdate(){
$model->updated_by = Yii::$app->user->identity->id;
                $model->updated_at = new \yii\db\Expression('NOW()');
                $model->created_by = $model->created_by;
                $model->created_at = $model->created_at;
                $model->save();
}
